### ISSUE TITLE
remove twitter and CHAH images and links from footer

### ISSUE THREAD

**Issue by ess-acppo** [ess-acppo/services#2]

**Comment by ArnabRaxit** [comment]
The CHAH logo and twitter handle has been removed. @ess-acppo-djd: please have a look. 
https://nxl-beta-231725113.ap-southeast-2.elb.amazonaws.com/nsl/services/

**Comment by ess-acppo-djd** [comment]
Yep. Looks good.

**Comment by ess-acppo-djd** [comment]
Closed as task is complete.
