### ISSUE TITLE
Construction of references should mirror the form used by the NSL

### ISSUE THREAD

**Issue by ess-acppo-djd** [ess-acppo/services#6]
The format for a reference must be the same as the format used in the NSL.

The pattern is:

[Author/s names] [open parenthesis] [year of publication] [close parenthesis] [comma] [name of publication in italic] [colon] [page number/s]

**Comment by ess-acppo-djd** [comment]
All okay at the moment except for italics

**Comment by ess-acppo** [comment]
Looks like the _parent_ of a "reference" is _italicised_. 
https://github.com/ess-acppo/services/blob/ec14d2a4827f0c19a427528484fdf089200d2916/grails-app/services/au/org/biodiversity/nsl/ReferenceService.groovy#L108
If we can construct meaningful parents of the references the app will automatically render the parent references in _italics_

**Comment by ArnabRaxit** [comment]
Looks like the _parent_ of a "reference" is _italicised_. 
https://github.com/ess-acppo/services/blob/ec14d2a4827f0c19a427528484fdf089200d2916/grails-app/services/au/org/biodiversity/nsl/ReferenceService.groovy#L108
If we can construct meaningful parents of the references the app will automatically render the parent references in _italics_

**Comment by ess-acppo-djd** [comment]
We may need to quiz the ANBG guys as to what is meant here (by 'parentTitle')
My take on this is that the 'reference' is seen as a 'child' of the 'publication' to which it points. The publication has a 'title' - thus 'parentTitle' is the name of the publication within which there is a reference to  the name.
Maybe we're loading the wrong parts of the data model?

**Comment by ArnabRaxit** [comment]
Peters suggestion is 

1. Matchup Taxatree data with what vascular plants already have. Use any matches found there.
2. For those which has no matches artificially create references.

**Comment by ArnabRaxit** [comment]
Question: How can we have the reference title in italics ONLY?
![image](https://user-images.githubusercontent.com/5765791/33532613-29db5d00-d8ef-11e7-8c12-062b33f5df34.png)

**Comment by ArnabRaxit** [comment]
On checking the api json response the  citation string is enclosed by <i> which renders it italicized.
[https://biodiversity.org.au/nsl/services/name/apni/137741.json](url)
![image](https://user-images.githubusercontent.com/5765791/33537008-11ff2310-d90d-11e7-8c75-21c1f7f6d3a7.png)

**Comment by ess-acppo-djd** [comment]
This would appear to be a data entry convention adopted by the users responsible for the data.
We should note that this is something we need to ask Anna Monro about.

**Comment by ess-acppo-djd** [comment]
Italicisation is **not** achieved by entering the markup into the field. 
This is the technique used by APNI to have the publication title italicised: 
set up the publication as a PARENT title, and then 
create a SECTION where the title contains the text "Not set". 

The SECTION reference is then used when creating the INSTANCE for the name.
When the name is displayed, the publication reference will be italicised.

**Comment by ess-acppo-djd** [comment]
Resolved
